/**
 * Irisnet API
 * Artificial Intelligence (AI) for image- and video-processing in real-time. This is an interactive documentation where you can quickly look up the endpoints and their schemas, while having the opportunity to try things out for yourself.  In the list below, you can see the available endpoints of the API, which can be expanded by clicking on them. Each expanded endpoint lists the request parameters (if available) and the request body (if available). The request body can list some example bodies and the schema, explaining each model in detail.  Additionally you'll find a 'Try it out' button that allows you to enter your custom parameters and custom body and execute that against the API. <b>Be sure to enter your license key to authorize the requests before using this documentation interactively.</b>  The responses section in the expanded endpoint lists the possible responses with their corresponding status codes. If you've executed an API call it will also show you the response from the server.  Underneath the endpoints you'll find the model schemas. These are the models used for the requests and responses. If you click on the right arrow, you can expand the model and get a description of the model and the model parameters. For nested models, you can keep clicking the right arrow for further details.  Clicking the link below the title at the top of this page opens the [OpenAPI specification](https://swagger.io/specification/) (OAS3) in JSON format. The OAS3 Spec allows the generation of clients in many programming languages. There are several free client generators available that can be used to get started easily.
 *
 * The version of the OpenAPI document: v2
 * Contact: info@irisnet.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package de.irisnet.java.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Attributes qualifying the _ageEstimation_ classification.
 **/
@ApiModel(description = "Attributes qualifying the _ageEstimation_ classification.")
public class AgeEstimationAttribute {
  
  @SerializedName("type")
  private String type = null;
  @SerializedName("age")
  private Integer age = null;
  @SerializedName("ageMin")
  private Integer ageMin = null;
  @SerializedName("ageMax")
  private Integer ageMax = null;

  /**
   * Used as a type discriminator for json to object conversion.
   **/
  @ApiModelProperty(value = "Used as a type discriminator for json to object conversion.")
  public String getType() {
    return type;
  }
  public void setType(String type) {
    this.type = type;
  }

  /**
   * The estimated age of the person in the selfie in years.
   **/
  @ApiModelProperty(value = "The estimated age of the person in the selfie in years.")
  public Integer getAge() {
    return age;
  }
  public void setAge(Integer age) {
    this.age = age;
  }

  /**
   * The estimated minimum age of the person in the selfie in years.
   **/
  @ApiModelProperty(value = "The estimated minimum age of the person in the selfie in years.")
  public Integer getAgeMin() {
    return ageMin;
  }
  public void setAgeMin(Integer ageMin) {
    this.ageMin = ageMin;
  }

  /**
   * The estimated maximum age of the person in the selfie in years.
   **/
  @ApiModelProperty(value = "The estimated maximum age of the person in the selfie in years.")
  public Integer getAgeMax() {
    return ageMax;
  }
  public void setAgeMax(Integer ageMax) {
    this.ageMax = ageMax;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AgeEstimationAttribute ageEstimationAttribute = (AgeEstimationAttribute) o;
    return (this.type == null ? ageEstimationAttribute.type == null : this.type.equals(ageEstimationAttribute.type)) &&
        (this.age == null ? ageEstimationAttribute.age == null : this.age.equals(ageEstimationAttribute.age)) &&
        (this.ageMin == null ? ageEstimationAttribute.ageMin == null : this.ageMin.equals(ageEstimationAttribute.ageMin)) &&
        (this.ageMax == null ? ageEstimationAttribute.ageMax == null : this.ageMax.equals(ageEstimationAttribute.ageMax));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.type == null ? 0: this.type.hashCode());
    result = 31 * result + (this.age == null ? 0: this.age.hashCode());
    result = 31 * result + (this.ageMin == null ? 0: this.ageMin.hashCode());
    result = 31 * result + (this.ageMax == null ? 0: this.ageMax.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class AgeEstimationAttribute {\n");
    
    sb.append("  type: ").append(type).append("\n");
    sb.append("  age: ").append(age).append("\n");
    sb.append("  ageMin: ").append(ageMin).append("\n");
    sb.append("  ageMax: ").append(ageMax).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
