/**
 * Irisnet API
 * Artificial Intelligence (AI) for image- and video-processing in real-time. This is an interactive documentation where you can quickly look up the endpoints and their schemas, while having the opportunity to try things out for yourself.  In the list below, you can see the available endpoints of the API, which can be expanded by clicking on them. Each expanded endpoint lists the request parameters (if available) and the request body (if available). The request body can list some example bodies and the schema, explaining each model in detail.  Additionally you'll find a 'Try it out' button that allows you to enter your custom parameters and custom body and execute that against the API. <b>Be sure to enter your license key to authorize the requests before using this documentation interactively.</b>  The responses section in the expanded endpoint lists the possible responses with their corresponding status codes. If you've executed an API call it will also show you the response from the server.  Underneath the endpoints you'll find the model schemas. These are the models used for the requests and responses. If you click on the right arrow, you can expand the model and get a description of the model and the model parameters. For nested models, you can keep clicking the right arrow for further details.  Clicking the link below the title at the top of this page opens the [OpenAPI specification](https://swagger.io/specification/) (OAS3) in JSON format. The OAS3 Spec allows the generation of clients in many programming languages. There are several free client generators available that can be used to get started easily.
 *
 * The version of the OpenAPI document: v2
 * Contact: info@irisnet.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package de.irisnet.java.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Contains information on ageVerification sub-checks
 **/
@ApiModel(description = "Contains information on ageVerification sub-checks")
public class AgeVerificationSubChecks {
  
  public enum FaceLivenessCheckEnum {
     passed,  failed,  not_processed, 
  };
  @SerializedName("faceLivenessCheck")
  private FaceLivenessCheckEnum faceLivenessCheck = null;
  public enum AgeValidationCheckEnum {
     passed,  failed,  not_processed, 
  };
  @SerializedName("ageValidationCheck")
  private AgeValidationCheckEnum ageValidationCheck = null;

  /**
   * Indicates if the selfie image is genuine and not a photo of an image or of a screen
   **/
  @ApiModelProperty(value = "Indicates if the selfie image is genuine and not a photo of an image or of a screen")
  public FaceLivenessCheckEnum getFaceLivenessCheck() {
    return faceLivenessCheck;
  }
  public void setFaceLivenessCheck(FaceLivenessCheckEnum faceLivenessCheck) {
    this.faceLivenessCheck = faceLivenessCheck;
  }

  /**
   * Indicates if the estimated age is greater than or equal to a predefined minimum accepted age
   **/
  @ApiModelProperty(value = "Indicates if the estimated age is greater than or equal to a predefined minimum accepted age")
  public AgeValidationCheckEnum getAgeValidationCheck() {
    return ageValidationCheck;
  }
  public void setAgeValidationCheck(AgeValidationCheckEnum ageValidationCheck) {
    this.ageValidationCheck = ageValidationCheck;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AgeVerificationSubChecks ageVerificationSubChecks = (AgeVerificationSubChecks) o;
    return (this.faceLivenessCheck == null ? ageVerificationSubChecks.faceLivenessCheck == null : this.faceLivenessCheck.equals(ageVerificationSubChecks.faceLivenessCheck)) &&
        (this.ageValidationCheck == null ? ageVerificationSubChecks.ageValidationCheck == null : this.ageValidationCheck.equals(ageVerificationSubChecks.ageValidationCheck));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.faceLivenessCheck == null ? 0: this.faceLivenessCheck.hashCode());
    result = 31 * result + (this.ageValidationCheck == null ? 0: this.ageValidationCheck.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class AgeVerificationSubChecks {\n");
    
    sb.append("  faceLivenessCheck: ").append(faceLivenessCheck).append("\n");
    sb.append("  ageValidationCheck: ").append(ageValidationCheck).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
