/**
 * Irisnet API
 * Artificial Intelligence (AI) for image- and video-processing in real-time. This is an interactive documentation where you can quickly look up the endpoints and their schemas, while having the opportunity to try things out for yourself.  In the list below, you can see the available endpoints of the API, which can be expanded by clicking on them. Each expanded endpoint lists the request parameters (if available) and the request body (if available). The request body can list some example bodies and the schema, explaining each model in detail.  Additionally you'll find a 'Try it out' button that allows you to enter your custom parameters and custom body and execute that against the API. <b>Be sure to enter your license key to authorize the requests before using this documentation interactively.</b>  The responses section in the expanded endpoint lists the possible responses with their corresponding status codes. If you've executed an API call it will also show you the response from the server.  Underneath the endpoints you'll find the model schemas. These are the models used for the requests and responses. If you click on the right arrow, you can expand the model and get a description of the model and the model parameters. For nested models, you can keep clicking the right arrow for further details.  Clicking the link below the title at the top of this page opens the [OpenAPI specification](https://swagger.io/specification/) (OAS3) in JSON format. The OAS3 Spec allows the generation of clients in many programming languages. There are several free client generators available that can be used to get started easily.
 *
 * The version of the OpenAPI document: v2
 * Contact: info@irisnet.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package de.irisnet.java.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class AiClassification {
  
  @SerializedName("name")
  private String name = null;
  @SerializedName("min")
  private Integer min = null;
  @SerializedName("max")
  private Integer max = null;
  @SerializedName("drawMode")
  private Integer drawMode = null;
  @SerializedName("grouped")
  private Boolean grouped = null;
  @SerializedName("description")
  private String description = null;
  @SerializedName("cascadedFrom")
  private String cascadedFrom = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getMin() {
    return min;
  }
  public void setMin(Integer min) {
    this.min = min;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getMax() {
    return max;
  }
  public void setMax(Integer max) {
    this.max = max;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getDrawMode() {
    return drawMode;
  }
  public void setDrawMode(Integer drawMode) {
    this.drawMode = drawMode;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getGrouped() {
    return grouped;
  }
  public void setGrouped(Boolean grouped) {
    this.grouped = grouped;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }
  public void setDescription(String description) {
    this.description = description;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCascadedFrom() {
    return cascadedFrom;
  }
  public void setCascadedFrom(String cascadedFrom) {
    this.cascadedFrom = cascadedFrom;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AiClassification aiClassification = (AiClassification) o;
    return (this.name == null ? aiClassification.name == null : this.name.equals(aiClassification.name)) &&
        (this.min == null ? aiClassification.min == null : this.min.equals(aiClassification.min)) &&
        (this.max == null ? aiClassification.max == null : this.max.equals(aiClassification.max)) &&
        (this.drawMode == null ? aiClassification.drawMode == null : this.drawMode.equals(aiClassification.drawMode)) &&
        (this.grouped == null ? aiClassification.grouped == null : this.grouped.equals(aiClassification.grouped)) &&
        (this.description == null ? aiClassification.description == null : this.description.equals(aiClassification.description)) &&
        (this.cascadedFrom == null ? aiClassification.cascadedFrom == null : this.cascadedFrom.equals(aiClassification.cascadedFrom));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.min == null ? 0: this.min.hashCode());
    result = 31 * result + (this.max == null ? 0: this.max.hashCode());
    result = 31 * result + (this.drawMode == null ? 0: this.drawMode.hashCode());
    result = 31 * result + (this.grouped == null ? 0: this.grouped.hashCode());
    result = 31 * result + (this.description == null ? 0: this.description.hashCode());
    result = 31 * result + (this.cascadedFrom == null ? 0: this.cascadedFrom.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class AiClassification {\n");
    
    sb.append("  name: ").append(name).append("\n");
    sb.append("  min: ").append(min).append("\n");
    sb.append("  max: ").append(max).append("\n");
    sb.append("  drawMode: ").append(drawMode).append("\n");
    sb.append("  grouped: ").append(grouped).append("\n");
    sb.append("  description: ").append(description).append("\n");
    sb.append("  cascadedFrom: ").append(cascadedFrom).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
