/**
 * Irisnet API
 * Artificial Intelligence (AI) for image- and video-processing in real-time. This is an interactive documentation where you can quickly look up the endpoints and their schemas, while having the opportunity to try things out for yourself.  In the list below, you can see the available endpoints of the API, which can be expanded by clicking on them. Each expanded endpoint lists the request parameters (if available) and the request body (if available). The request body can list some example bodies and the schema, explaining each model in detail.  Additionally you'll find a 'Try it out' button that allows you to enter your custom parameters and custom body and execute that against the API. <b>Be sure to enter your license key to authorize the requests before using this documentation interactively.</b>  The responses section in the expanded endpoint lists the possible responses with their corresponding status codes. If you've executed an API call it will also show you the response from the server.  Underneath the endpoints you'll find the model schemas. These are the models used for the requests and responses. If you click on the right arrow, you can expand the model and get a description of the model and the model parameters. For nested models, you can keep clicking the right arrow for further details.  Clicking the link below the title at the top of this page opens the [OpenAPI specification](https://swagger.io/specification/) (OAS3) in JSON format. The OAS3 Spec allows the generation of clients in many programming languages. There are several free client generators available that can be used to get started easily.
 *
 * The version of the OpenAPI document: v2
 * Contact: info@irisnet.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package de.irisnet.java.client.model;

import de.irisnet.java.client.model.AiClassification;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class AiPrototype {
  
  @SerializedName("name")
  private String name = null;
  @SerializedName("classifications")
  private Set<AiClassification> classifications = null;
  @SerializedName("summary")
  private String summary = null;
  @SerializedName("aliases")
  private Set<String> aliases = null;
  @SerializedName("modes")
  private Set<String> modes = null;
  public enum RouteEnum {
     AI_SERVICE,  TEXT_SERVICE,  PROVIDER_SERVICE, 
  };
  @SerializedName("route")
  private RouteEnum route = null;
  @SerializedName("routerMethod")
  private String routerMethod = null;
  @SerializedName("dependsOn")
  private Set<String> dependsOn = null;
  @SerializedName("hidden")
  private Boolean hidden = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Set<AiClassification> getClassifications() {
    return classifications;
  }
  public void setClassifications(Set<AiClassification> classifications) {
    this.classifications = classifications;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getSummary() {
    return summary;
  }
  public void setSummary(String summary) {
    this.summary = summary;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Set<String> getAliases() {
    return aliases;
  }
  public void setAliases(Set<String> aliases) {
    this.aliases = aliases;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Set<String> getModes() {
    return modes;
  }
  public void setModes(Set<String> modes) {
    this.modes = modes;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public RouteEnum getRoute() {
    return route;
  }
  public void setRoute(RouteEnum route) {
    this.route = route;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getRouterMethod() {
    return routerMethod;
  }
  public void setRouterMethod(String routerMethod) {
    this.routerMethod = routerMethod;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Set<String> getDependsOn() {
    return dependsOn;
  }
  public void setDependsOn(Set<String> dependsOn) {
    this.dependsOn = dependsOn;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getHidden() {
    return hidden;
  }
  public void setHidden(Boolean hidden) {
    this.hidden = hidden;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AiPrototype aiPrototype = (AiPrototype) o;
    return (this.name == null ? aiPrototype.name == null : this.name.equals(aiPrototype.name)) &&
        (this.classifications == null ? aiPrototype.classifications == null : this.classifications.equals(aiPrototype.classifications)) &&
        (this.summary == null ? aiPrototype.summary == null : this.summary.equals(aiPrototype.summary)) &&
        (this.aliases == null ? aiPrototype.aliases == null : this.aliases.equals(aiPrototype.aliases)) &&
        (this.modes == null ? aiPrototype.modes == null : this.modes.equals(aiPrototype.modes)) &&
        (this.route == null ? aiPrototype.route == null : this.route.equals(aiPrototype.route)) &&
        (this.routerMethod == null ? aiPrototype.routerMethod == null : this.routerMethod.equals(aiPrototype.routerMethod)) &&
        (this.dependsOn == null ? aiPrototype.dependsOn == null : this.dependsOn.equals(aiPrototype.dependsOn)) &&
        (this.hidden == null ? aiPrototype.hidden == null : this.hidden.equals(aiPrototype.hidden));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.classifications == null ? 0: this.classifications.hashCode());
    result = 31 * result + (this.summary == null ? 0: this.summary.hashCode());
    result = 31 * result + (this.aliases == null ? 0: this.aliases.hashCode());
    result = 31 * result + (this.modes == null ? 0: this.modes.hashCode());
    result = 31 * result + (this.route == null ? 0: this.route.hashCode());
    result = 31 * result + (this.routerMethod == null ? 0: this.routerMethod.hashCode());
    result = 31 * result + (this.dependsOn == null ? 0: this.dependsOn.hashCode());
    result = 31 * result + (this.hidden == null ? 0: this.hidden.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class AiPrototype {\n");
    
    sb.append("  name: ").append(name).append("\n");
    sb.append("  classifications: ").append(classifications).append("\n");
    sb.append("  summary: ").append(summary).append("\n");
    sb.append("  aliases: ").append(aliases).append("\n");
    sb.append("  modes: ").append(modes).append("\n");
    sb.append("  route: ").append(route).append("\n");
    sb.append("  routerMethod: ").append(routerMethod).append("\n");
    sb.append("  dependsOn: ").append(dependsOn).append("\n");
    sb.append("  hidden: ").append(hidden).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
