/**
 * Irisnet API
 * Artificial Intelligence (AI) for image- and video-processing in real-time. This is an interactive documentation where you can quickly look up the endpoints and their schemas, while having the opportunity to try things out for yourself.  In the list below, you can see the available endpoints of the API, which can be expanded by clicking on them. Each expanded endpoint lists the request parameters (if available) and the request body (if available). The request body can list some example bodies and the schema, explaining each model in detail.  Additionally you'll find a 'Try it out' button that allows you to enter your custom parameters and custom body and execute that against the API. <b>Be sure to enter your license key to authorize the requests before using this documentation interactively.</b>  The responses section in the expanded endpoint lists the possible responses with their corresponding status codes. If you've executed an API call it will also show you the response from the server.  Underneath the endpoints you'll find the model schemas. These are the models used for the requests and responses. If you click on the right arrow, you can expand the model and get a description of the model and the model parameters. For nested models, you can keep clicking the right arrow for further details.  Clicking the link below the title at the top of this page opens the [OpenAPI specification](https://swagger.io/specification/) (OAS3) in JSON format. The OAS3 Spec allows the generation of clients in many programming languages. There are several free client generators available that can be used to get started easily.
 *
 * The version of the OpenAPI document: v2
 * Contact: info@irisnet.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package de.irisnet.java.client.model;

import de.irisnet.java.client.model.Callback;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class BiometricCheckRequestData {
  
  @SerializedName("callback")
  private Callback callback = null;
  @SerializedName("frontImage")
  private String frontImage = null;
  @SerializedName("selfieImage")
  private String selfieImage = null;
  @SerializedName("minimumAcceptedAge")
  private Integer minimumAcceptedAge = null;
  @SerializedName("documentHolderId")
  private String documentHolderId = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Callback getCallback() {
    return callback;
  }
  public void setCallback(Callback callback) {
    this.callback = callback;
  }

  /**
   * The base64-encoded front image of the document to be checked in either jpg or png file format.
   **/
  @ApiModelProperty(value = "The base64-encoded front image of the document to be checked in either jpg or png file format.")
  public String getFrontImage() {
    return frontImage;
  }
  public void setFrontImage(String frontImage) {
    this.frontImage = frontImage;
  }

  /**
   * The base64-encoded selfie image to be checked in either jpg or png file format.
   **/
  @ApiModelProperty(required = true, value = "The base64-encoded selfie image to be checked in either jpg or png file format.")
  public String getSelfieImage() {
    return selfieImage;
  }
  public void setSelfieImage(String selfieImage) {
    this.selfieImage = selfieImage;
  }

  /**
   * The minimum age in years accepted for a DocumentCheck, if applicable. Defaults to 18 if not specified.
   **/
  @ApiModelProperty(value = "The minimum age in years accepted for a DocumentCheck, if applicable. Defaults to 18 if not specified.")
  public Integer getMinimumAcceptedAge() {
    return minimumAcceptedAge;
  }
  public void setMinimumAcceptedAge(Integer minimumAcceptedAge) {
    this.minimumAcceptedAge = minimumAcceptedAge;
  }

  /**
   * The documentHolderId from a previous successful DocumentCheck.
   **/
  @ApiModelProperty(value = "The documentHolderId from a previous successful DocumentCheck.")
  public String getDocumentHolderId() {
    return documentHolderId;
  }
  public void setDocumentHolderId(String documentHolderId) {
    this.documentHolderId = documentHolderId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BiometricCheckRequestData biometricCheckRequestData = (BiometricCheckRequestData) o;
    return (this.callback == null ? biometricCheckRequestData.callback == null : this.callback.equals(biometricCheckRequestData.callback)) &&
        (this.frontImage == null ? biometricCheckRequestData.frontImage == null : this.frontImage.equals(biometricCheckRequestData.frontImage)) &&
        (this.selfieImage == null ? biometricCheckRequestData.selfieImage == null : this.selfieImage.equals(biometricCheckRequestData.selfieImage)) &&
        (this.minimumAcceptedAge == null ? biometricCheckRequestData.minimumAcceptedAge == null : this.minimumAcceptedAge.equals(biometricCheckRequestData.minimumAcceptedAge)) &&
        (this.documentHolderId == null ? biometricCheckRequestData.documentHolderId == null : this.documentHolderId.equals(biometricCheckRequestData.documentHolderId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.callback == null ? 0: this.callback.hashCode());
    result = 31 * result + (this.frontImage == null ? 0: this.frontImage.hashCode());
    result = 31 * result + (this.selfieImage == null ? 0: this.selfieImage.hashCode());
    result = 31 * result + (this.minimumAcceptedAge == null ? 0: this.minimumAcceptedAge.hashCode());
    result = 31 * result + (this.documentHolderId == null ? 0: this.documentHolderId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class BiometricCheckRequestData {\n");
    
    sb.append("  callback: ").append(callback).append("\n");
    sb.append("  frontImage: ").append(frontImage).append("\n");
    sb.append("  selfieImage: ").append(selfieImage).append("\n");
    sb.append("  minimumAcceptedAge: ").append(minimumAcceptedAge).append("\n");
    sb.append("  documentHolderId: ").append(documentHolderId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
