/**
 * Irisnet API
 * Artificial Intelligence (AI) for image- and video-processing in real-time. This is an interactive documentation where you can quickly look up the endpoints and their schemas, while having the opportunity to try things out for yourself.  In the list below, you can see the available endpoints of the API, which can be expanded by clicking on them. Each expanded endpoint lists the request parameters (if available) and the request body (if available). The request body can list some example bodies and the schema, explaining each model in detail.  Additionally you'll find a 'Try it out' button that allows you to enter your custom parameters and custom body and execute that against the API. <b>Be sure to enter your license key to authorize the requests before using this documentation interactively.</b>  The responses section in the expanded endpoint lists the possible responses with their corresponding status codes. If you've executed an API call it will also show you the response from the server.  Underneath the endpoints you'll find the model schemas. These are the models used for the requests and responses. If you click on the right arrow, you can expand the model and get a description of the model and the model parameters. For nested models, you can keep clicking the right arrow for further details.  Clicking the link below the title at the top of this page opens the [OpenAPI specification](https://swagger.io/specification/) (OAS3) in JSON format. The OAS3 Spec allows the generation of clients in many programming languages. There are several free client generators available that can be used to get started easily.
 *
 * The version of the OpenAPI document: v2
 * Contact: info@irisnet.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package de.irisnet.java.client.model;

import java.net.URI;
import java.util.Map;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Callback options to send a response to.
 **/
@ApiModel(description = "Callback options to send a response to.")
public class Callback {
  
  @SerializedName("callbackUrl")
  private URI callbackUrl = null;
  @SerializedName("headers")
  private Map<String, String> headers = null;

  /**
   * Define a URL where a response should be sent.
   **/
  @ApiModelProperty(required = true, value = "Define a URL where a response should be sent.")
  public URI getCallbackUrl() {
    return callbackUrl;
  }
  public void setCallbackUrl(URI callbackUrl) {
    this.callbackUrl = callbackUrl;
  }

  /**
   * Define headers to send to the URL.
   **/
  @ApiModelProperty(value = "Define headers to send to the URL.")
  public Map<String, String> getHeaders() {
    return headers;
  }
  public void setHeaders(Map<String, String> headers) {
    this.headers = headers;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Callback callback = (Callback) o;
    return (this.callbackUrl == null ? callback.callbackUrl == null : this.callbackUrl.equals(callback.callbackUrl)) &&
        (this.headers == null ? callback.headers == null : this.headers.equals(callback.headers));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.callbackUrl == null ? 0: this.callbackUrl.hashCode());
    result = 31 * result + (this.headers == null ? 0: this.headers.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Callback {\n");
    
    sb.append("  callbackUrl: ").append(callbackUrl).append("\n");
    sb.append("  headers: ").append(headers).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
