/**
 * Irisnet API
 * Artificial Intelligence (AI) for image- and video-processing in real-time. This is an interactive documentation where you can quickly look up the endpoints and their schemas, while having the opportunity to try things out for yourself.  In the list below, you can see the available endpoints of the API, which can be expanded by clicking on them. Each expanded endpoint lists the request parameters (if available) and the request body (if available). The request body can list some example bodies and the schema, explaining each model in detail.  Additionally you'll find a 'Try it out' button that allows you to enter your custom parameters and custom body and execute that against the API. <b>Be sure to enter your license key to authorize the requests before using this documentation interactively.</b>  The responses section in the expanded endpoint lists the possible responses with their corresponding status codes. If you've executed an API call it will also show you the response from the server.  Underneath the endpoints you'll find the model schemas. These are the models used for the requests and responses. If you click on the right arrow, you can expand the model and get a description of the model and the model parameters. For nested models, you can keep clicking the right arrow for further details.  Clicking the link below the title at the top of this page opens the [OpenAPI specification](https://swagger.io/specification/) (OAS3) in JSON format. The OAS3 Spec allows the generation of clients in many programming languages. There are several free client generators available that can be used to get started easily.
 *
 * The version of the OpenAPI document: v2
 * Contact: info@irisnet.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package de.irisnet.java.client.model;

import de.irisnet.java.client.model.ApiNotice;
import de.irisnet.java.client.model.BaseDetection;
import de.irisnet.java.client.model.BrokenRule;
import de.irisnet.java.client.model.Encoded;
import de.irisnet.java.client.model.Event;
import de.irisnet.java.client.model.Summary;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * The root object returned after a check operation.
 **/
@ApiModel(description = "The root object returned after a check operation.")
public class CheckResult {
  
  @SerializedName("summary")
  private Summary summary = null;
  @SerializedName("encodings")
  private List<Encoded> encodings = null;
  @SerializedName("brokenRules")
  private List<BrokenRule> brokenRules = null;
  @SerializedName("detections")
  private List<BaseDetection> detections = null;
  @SerializedName("events")
  private List<Event> events = null;
  @SerializedName("notifications")
  private List<ApiNotice> notifications = null;
  @SerializedName("checkId")
  private String checkId = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Summary getSummary() {
    return summary;
  }
  public void setSummary(Summary summary) {
    this.summary = summary;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Encoded> getEncodings() {
    return encodings;
  }
  public void setEncodings(List<Encoded> encodings) {
    this.encodings = encodings;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<BrokenRule> getBrokenRules() {
    return brokenRules;
  }
  public void setBrokenRules(List<BrokenRule> brokenRules) {
    this.brokenRules = brokenRules;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<BaseDetection> getDetections() {
    return detections;
  }
  public void setDetections(List<BaseDetection> detections) {
    this.detections = detections;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Event> getEvents() {
    return events;
  }
  public void setEvents(List<Event> events) {
    this.events = events;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<ApiNotice> getNotifications() {
    return notifications;
  }
  public void setNotifications(List<ApiNotice> notifications) {
    this.notifications = notifications;
  }

  /**
   * The id of the async running check
   **/
  @ApiModelProperty(value = "The id of the async running check")
  public String getCheckId() {
    return checkId;
  }
  public void setCheckId(String checkId) {
    this.checkId = checkId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CheckResult checkResult = (CheckResult) o;
    return (this.summary == null ? checkResult.summary == null : this.summary.equals(checkResult.summary)) &&
        (this.encodings == null ? checkResult.encodings == null : this.encodings.equals(checkResult.encodings)) &&
        (this.brokenRules == null ? checkResult.brokenRules == null : this.brokenRules.equals(checkResult.brokenRules)) &&
        (this.detections == null ? checkResult.detections == null : this.detections.equals(checkResult.detections)) &&
        (this.events == null ? checkResult.events == null : this.events.equals(checkResult.events)) &&
        (this.notifications == null ? checkResult.notifications == null : this.notifications.equals(checkResult.notifications)) &&
        (this.checkId == null ? checkResult.checkId == null : this.checkId.equals(checkResult.checkId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.summary == null ? 0: this.summary.hashCode());
    result = 31 * result + (this.encodings == null ? 0: this.encodings.hashCode());
    result = 31 * result + (this.brokenRules == null ? 0: this.brokenRules.hashCode());
    result = 31 * result + (this.detections == null ? 0: this.detections.hashCode());
    result = 31 * result + (this.events == null ? 0: this.events.hashCode());
    result = 31 * result + (this.notifications == null ? 0: this.notifications.hashCode());
    result = 31 * result + (this.checkId == null ? 0: this.checkId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class CheckResult {\n");
    
    sb.append("  summary: ").append(summary).append("\n");
    sb.append("  encodings: ").append(encodings).append("\n");
    sb.append("  brokenRules: ").append(brokenRules).append("\n");
    sb.append("  detections: ").append(detections).append("\n");
    sb.append("  events: ").append(events).append("\n");
    sb.append("  notifications: ").append(notifications).append("\n");
    sb.append("  checkId: ").append(checkId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
