/**
 * Irisnet API
 * Artificial Intelligence (AI) for image- and video-processing in real-time. This is an interactive documentation where you can quickly look up the endpoints and their schemas, while having the opportunity to try things out for yourself.  In the list below, you can see the available endpoints of the API, which can be expanded by clicking on them. Each expanded endpoint lists the request parameters (if available) and the request body (if available). The request body can list some example bodies and the schema, explaining each model in detail.  Additionally you'll find a 'Try it out' button that allows you to enter your custom parameters and custom body and execute that against the API. <b>Be sure to enter your license key to authorize the requests before using this documentation interactively.</b>  The responses section in the expanded endpoint lists the possible responses with their corresponding status codes. If you've executed an API call it will also show you the response from the server.  Underneath the endpoints you'll find the model schemas. These are the models used for the requests and responses. If you click on the right arrow, you can expand the model and get a description of the model and the model parameters. For nested models, you can keep clicking the right arrow for further details.  Clicking the link below the title at the top of this page opens the [OpenAPI specification](https://swagger.io/specification/) (OAS3) in JSON format. The OAS3 Spec allows the generation of clients in many programming languages. There are several free client generators available that can be used to get started easily.
 *
 * The version of the OpenAPI document: v2
 * Contact: info@irisnet.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package de.irisnet.java.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Attributes qualifying the _hair_ classification.
 **/
@ApiModel(description = "Attributes qualifying the _hair_ classification.")
public class HairAttribute {
  
  @SerializedName("type")
  private String type = null;
  public enum ColorEnum {
     black,  darkBrown,  brown,  lightBrown,  darkBlonde,  blonde,  darkGrey,  grey,  red,  white,  other, 
  };
  @SerializedName("color")
  private ColorEnum color = null;
  public enum StyleEnum {
     longHaired,  shortHaired, 
  };
  @SerializedName("style")
  private StyleEnum style = null;

  /**
   * Used as a type discriminator for json to object conversion.
   **/
  @ApiModelProperty(value = "Used as a type discriminator for json to object conversion.")
  public String getType() {
    return type;
  }
  public void setType(String type) {
    this.type = type;
  }

  /**
   * The color of the hair.
   **/
  @ApiModelProperty(value = "The color of the hair.")
  public ColorEnum getColor() {
    return color;
  }
  public void setColor(ColorEnum color) {
    this.color = color;
  }

  /**
   * The hair style.
   **/
  @ApiModelProperty(value = "The hair style.")
  public StyleEnum getStyle() {
    return style;
  }
  public void setStyle(StyleEnum style) {
    this.style = style;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HairAttribute hairAttribute = (HairAttribute) o;
    return (this.type == null ? hairAttribute.type == null : this.type.equals(hairAttribute.type)) &&
        (this.color == null ? hairAttribute.color == null : this.color.equals(hairAttribute.color)) &&
        (this.style == null ? hairAttribute.style == null : this.style.equals(hairAttribute.style));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.type == null ? 0: this.type.hashCode());
    result = 31 * result + (this.color == null ? 0: this.color.hashCode());
    result = 31 * result + (this.style == null ? 0: this.style.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class HairAttribute {\n");
    
    sb.append("  type: ").append(type).append("\n");
    sb.append("  color: ").append(color).append("\n");
    sb.append("  style: ").append(style).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
