/**
 * Irisnet API
 * Artificial Intelligence (AI) for image- and video-processing in realtime. This is an interactive documentation meant to give a place were you can quickly look up the endpoints and their schemas, while also giving you the option to try things out yourself.  Listed below you'll see the available endpoints of the API that can be expanded by clicking on it. Each expanded endpoint lists the request parameter (if available) and the request body (if available). The request body can list some example bodies and the schema, explaining each model in detail. Additionally you'll find a 'Try it out' button where you can type in your custom parameters and custom body and execute that against the API. The responses section in the expanded endpoint lists the possible responses with their corresponding status codes. If you've executed an API call it will also show you the response from the server.  Underneath the endpoints you'll find the model schemas. These are the models used for the requests and responses. By clicking on the right arrow you can expand the model and it will show you a description of the model and the model parameters. For nested models you can keep clicking the right arrow to reveal further details on it.  
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package de.irisnet.java.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Describes a rectangle that stretches around the recognized object. This is useful when redacting or blurring certain recognized objects. Each object contains the name of the classification and coordinates for a rectangle around the recognized object. The origin point (y &#x3D; 0.0, x &#x3D; 0.0) of the coordinate system is on the top left of the of the source material. The bottom right of the source is always y &#x3D; 1 and x &#x3D; 1.
 **/
@ApiModel(description = "Describes a rectangle that stretches around the recognized object. This is useful when redacting or blurring certain recognized objects. Each object contains the name of the classification and coordinates for a rectangle around the recognized object. The origin point (y = 0.0, x = 0.0) of the coordinate system is on the top left of the of the source material. The bottom right of the source is always y = 1 and x = 1.")
public class INObject {
  
  @SerializedName("inClass")
  private String inClass = null;
  @SerializedName("inGroup")
  private String inGroup = null;
  @SerializedName("inId")
  private String inId = null;
  public enum ColorEnum {
     black,  brown,  blonde,  grey,  red,  other, 
  };
  @SerializedName("color")
  private ColorEnum color = null;
  public enum StyleEnum {
     longHaired,  shortHaired, 
  };
  @SerializedName("style")
  private StyleEnum style = null;
  @SerializedName("x0")
  private Float x0 = null;
  @SerializedName("y0")
  private Float y0 = null;
  @SerializedName("width")
  private Float width = null;
  @SerializedName("height")
  private Float height = null;
  @SerializedName("probability")
  private Integer probability = null;

  /**
   * The classification of the recognized object.
   **/
  @ApiModelProperty(value = "The classification of the recognized object.")
  public String getInClass() {
    return inClass;
  }
  public void setInClass(String inClass) {
    this.inClass = inClass;
  }

  /**
   * The group of the classification.
   **/
  @ApiModelProperty(value = "The group of the classification.")
  public String getInGroup() {
    return inGroup;
  }
  public void setInGroup(String inGroup) {
    this.inGroup = inGroup;
  }

  /**
   * The group of the classification.
   **/
  @ApiModelProperty(value = "The group of the classification.")
  public String getInId() {
    return inId;
  }
  public void setInId(String inId) {
    this.inId = inId;
  }

  /**
   * The color of the object, e.g. the color of the hair. Is only available for certain classification objects. See list below:  * _hair_ - black, brown, blonde, grey, red, other
   **/
  @ApiModelProperty(value = "The color of the object, e.g. the color of the hair. Is only available for certain classification objects. See list below:  * _hair_ - black, brown, blonde, grey, red, other")
  public ColorEnum getColor() {
    return color;
  }
  public void setColor(ColorEnum color) {
    this.color = color;
  }

  /**
   * The style attribute of the object, e.g. the style of the hair. Is only available for certain classification objects. See list below:  * _hair_ - longHaired, shortHaired
   **/
  @ApiModelProperty(value = "The style attribute of the object, e.g. the style of the hair. Is only available for certain classification objects. See list below:  * _hair_ - longHaired, shortHaired")
  public StyleEnum getStyle() {
    return style;
  }
  public void setStyle(StyleEnum style) {
    this.style = style;
  }

  /**
   * The starting point of the rectangle in the vertical (x) direction.
   **/
  @ApiModelProperty(value = "The starting point of the rectangle in the vertical (x) direction.")
  public Float getX0() {
    return x0;
  }
  public void setX0(Float x0) {
    this.x0 = x0;
  }

  /**
   * The starting point of the rectangle in the horizontal (y) direction.
   **/
  @ApiModelProperty(value = "The starting point of the rectangle in the horizontal (y) direction.")
  public Float getY0() {
    return y0;
  }
  public void setY0(Float y0) {
    this.y0 = y0;
  }

  /**
   * The distance from the starting point (y0) to end the rectangle in the horizontal direction.
   **/
  @ApiModelProperty(value = "The distance from the starting point (y0) to end the rectangle in the horizontal direction.")
  public Float getWidth() {
    return width;
  }
  public void setWidth(Float width) {
    this.width = width;
  }

  /**
   * The distance from the starting point (x0) to end the rectangle in the vertical direction.
   **/
  @ApiModelProperty(value = "The distance from the starting point (x0) to end the rectangle in the vertical direction.")
  public Float getHeight() {
    return height;
  }
  public void setHeight(Float height) {
    this.height = height;
  }

  /**
   * The probability that the object found matches the classification.
   **/
  @ApiModelProperty(value = "The probability that the object found matches the classification.")
  public Integer getProbability() {
    return probability;
  }
  public void setProbability(Integer probability) {
    this.probability = probability;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    INObject iNObject = (INObject) o;
    return (this.inClass == null ? iNObject.inClass == null : this.inClass.equals(iNObject.inClass)) &&
        (this.inGroup == null ? iNObject.inGroup == null : this.inGroup.equals(iNObject.inGroup)) &&
        (this.inId == null ? iNObject.inId == null : this.inId.equals(iNObject.inId)) &&
        (this.color == null ? iNObject.color == null : this.color.equals(iNObject.color)) &&
        (this.style == null ? iNObject.style == null : this.style.equals(iNObject.style)) &&
        (this.x0 == null ? iNObject.x0 == null : this.x0.equals(iNObject.x0)) &&
        (this.y0 == null ? iNObject.y0 == null : this.y0.equals(iNObject.y0)) &&
        (this.width == null ? iNObject.width == null : this.width.equals(iNObject.width)) &&
        (this.height == null ? iNObject.height == null : this.height.equals(iNObject.height)) &&
        (this.probability == null ? iNObject.probability == null : this.probability.equals(iNObject.probability));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.inClass == null ? 0: this.inClass.hashCode());
    result = 31 * result + (this.inGroup == null ? 0: this.inGroup.hashCode());
    result = 31 * result + (this.inId == null ? 0: this.inId.hashCode());
    result = 31 * result + (this.color == null ? 0: this.color.hashCode());
    result = 31 * result + (this.style == null ? 0: this.style.hashCode());
    result = 31 * result + (this.x0 == null ? 0: this.x0.hashCode());
    result = 31 * result + (this.y0 == null ? 0: this.y0.hashCode());
    result = 31 * result + (this.width == null ? 0: this.width.hashCode());
    result = 31 * result + (this.height == null ? 0: this.height.hashCode());
    result = 31 * result + (this.probability == null ? 0: this.probability.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class INObject {\n");
    
    sb.append("  inClass: ").append(inClass).append("\n");
    sb.append("  inGroup: ").append(inGroup).append("\n");
    sb.append("  inId: ").append(inId).append("\n");
    sb.append("  color: ").append(color).append("\n");
    sb.append("  style: ").append(style).append("\n");
    sb.append("  x0: ").append(x0).append("\n");
    sb.append("  y0: ").append(y0).append("\n");
    sb.append("  width: ").append(width).append("\n");
    sb.append("  height: ").append(height).append("\n");
    sb.append("  probability: ").append(probability).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
