/**
 * Irisnet API
 * Artificial Intelligence (AI) for image- and video-processing in realtime. This is an interactive documentation meant to give a place were you can quickly look up the endpoints and their schemas, while also giving you the option to try things out yourself.  Listed below you'll see the available endpoints of the API that can be expanded by clicking on it. Each expanded endpoint lists the request parameter (if available) and the request body (if available). The request body can list some example bodies and the schema, explaining each model in detail. Additionally you'll find a 'Try it out' button where you can type in your custom parameters and custom body and execute that against the API. The responses section in the expanded endpoint lists the possible responses with their corresponding status codes. If you've executed an API call it will also show you the response from the server.  Underneath the endpoints you'll find the model schemas. These are the models used for the requests and responses.By clicking on the right arrow you can expand the model and it will show you a description of the model and the model parameters. For nested models you can keep clicking the right arrow to reveal further details on it.  
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package de.irisnet.java.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * A single parameter set for one object, for example face, describing the behaviour of the AI. Each object has default parameters that are set if these are empty.
 **/
@ApiModel(description = "A single parameter set for one object, for example face, describing the behaviour of the AI. Each object has default parameters that are set if these are empty.")
public class INParam {
  
  public enum InClassEnum {
     face,  child,  adult,  senior,  pose,  hand,  breast,  vulva,  penis,  vagina,  buttocks,  anus,  toy,  oral,  penetration,  foot,  footwear,  nudityCheck,  ageVerification,  ageEstimation,  illegalSymbols, 
  };
  @SerializedName("inClass")
  private InClassEnum inClass = null;
  @SerializedName("min")
  private Integer min = null;
  @SerializedName("max")
  private Integer max = null;
  @SerializedName("drawMode")
  private Integer drawMode = null;
  @SerializedName("grey")
  private Integer grey = 127;

  /**
   * The classification of the object, that the element refers to. Default parameter values are defined per classification object. The following list contains the default values for 'min', 'max' and 'drawMode' in order.  * _face_ _(1, 3, 0)_ - Classification for human faces. * _child_ _(0, 0, 1)_ - Recognizes children's faces. Overwrites classification parameters of face. * _adult_ _(0, -1, 1)_ - Recognizes faces of adults that are not considered seniors. Overwrites classification parameters of face. * _senior_ _(0, -1, 1)_ - Recognizes faces of seniors. Overwrites classification parameters of face. * _pose_ _(0, 0, 1)_ - The age can not be estimated, due to a pose that hides facial features. * _hand_ _(0, -1, 0)_ - Classification for recognizing hands. * _foot_ _(0, -1, 0)_ - Classification for recognizing feet. * _footwear_ _(0, -1, 0)_ - Classification for recognizing footwear. * _breast_ _(0, 0, 2)_ - Object that recognizes female breasts. * _vulva_ _(0, 0, 2)_ - Object that recognizes vulvae. * _penis_ _(0, 0, 2)_ - Object that recognizes penises. * _vagina_ _(0, 0, 2)_ - Object that recognizes vaginae. * _buttocks_ _(0, 0, 2)_ - Object that recognizes buttocks. * _anus_ _(0, 0, 2)_ - Object that recognizes ani. * _toy_ _(0, 0, 2)_ - Object that recognizes sex toys. * _oral_ _(0, 0, 2)_ - Object that recognizes oral sex. * _penetration_ _(0, 0, 2)_ - Object that recognizes a sexual penetration penetration. * _illegalSymbols_ _(0, 0, 1)_ - Classification for symbols that are not permitted in Germany.  _Please be aware that the default values can be subject to change. This is due to the difficulty of recognizing certain objects e.g. objects that are classified as toy._
   **/
  @ApiModelProperty(value = "The classification of the object, that the element refers to. Default parameter values are defined per classification object. The following list contains the default values for 'min', 'max' and 'drawMode' in order.  * _face_ _(1, 3, 0)_ - Classification for human faces. * _child_ _(0, 0, 1)_ - Recognizes children's faces. Overwrites classification parameters of face. * _adult_ _(0, -1, 1)_ - Recognizes faces of adults that are not considered seniors. Overwrites classification parameters of face. * _senior_ _(0, -1, 1)_ - Recognizes faces of seniors. Overwrites classification parameters of face. * _pose_ _(0, 0, 1)_ - The age can not be estimated, due to a pose that hides facial features. * _hand_ _(0, -1, 0)_ - Classification for recognizing hands. * _foot_ _(0, -1, 0)_ - Classification for recognizing feet. * _footwear_ _(0, -1, 0)_ - Classification for recognizing footwear. * _breast_ _(0, 0, 2)_ - Object that recognizes female breasts. * _vulva_ _(0, 0, 2)_ - Object that recognizes vulvae. * _penis_ _(0, 0, 2)_ - Object that recognizes penises. * _vagina_ _(0, 0, 2)_ - Object that recognizes vaginae. * _buttocks_ _(0, 0, 2)_ - Object that recognizes buttocks. * _anus_ _(0, 0, 2)_ - Object that recognizes ani. * _toy_ _(0, 0, 2)_ - Object that recognizes sex toys. * _oral_ _(0, 0, 2)_ - Object that recognizes oral sex. * _penetration_ _(0, 0, 2)_ - Object that recognizes a sexual penetration penetration. * _illegalSymbols_ _(0, 0, 1)_ - Classification for symbols that are not permitted in Germany.  _Please be aware that the default values can be subject to change. This is due to the difficulty of recognizing certain objects e.g. objects that are classified as toy._")
  public InClassEnum getInClass() {
    return inClass;
  }
  public void setInClass(InClassEnum inClass) {
    this.inClass = inClass;
  }

  /**
   * The minimum amount of objects allowed on the source media. Setting the value to -1 will cause the AI to ignore this rule.
   **/
  @ApiModelProperty(value = "The minimum amount of objects allowed on the source media. Setting the value to -1 will cause the AI to ignore this rule.")
  public Integer getMin() {
    return min;
  }
  public void setMin(Integer min) {
    this.min = min;
  }

  /**
   * The maximum amount of objects allowed on the source media. Setting the value to -1 will cause the AI to ignore this rule.
   **/
  @ApiModelProperty(value = "The maximum amount of objects allowed on the source media. Setting the value to -1 will cause the AI to ignore this rule.")
  public Integer getMax() {
    return max;
  }
  public void setMax(Integer max) {
    this.max = max;
  }

  /**
   * The draw mode that will be used for the creating the media.  * _0_ - will draw nothing, * _1_ - will draw a frame with class name surrounding the object, * _2_ - will draw a filled rectangle that will mask the object, * _3_ - is a combination between _1_ and _2_ (frame/name + mask), * _6_ - will blur the object and * _7_ - is a combination between _1_ and _6_ (frame/name + blur).
   * minimum: 0
   * maximum: 7
   **/
  @ApiModelProperty(value = "The draw mode that will be used for the creating the media.  * _0_ - will draw nothing, * _1_ - will draw a frame with class name surrounding the object, * _2_ - will draw a filled rectangle that will mask the object, * _3_ - is a combination between _1_ and _2_ (frame/name + mask), * _6_ - will blur the object and * _7_ - is a combination between _1_ and _6_ (frame/name + blur).")
  public Integer getDrawMode() {
    return drawMode;
  }
  public void setDrawMode(Integer drawMode) {
    this.drawMode = drawMode;
  }

  /**
   * A grey scale color to use for masking. '0' will represent black, while the maximum '255' will be white.
   * minimum: 0
   * maximum: 255
   **/
  @ApiModelProperty(value = "A grey scale color to use for masking. '0' will represent black, while the maximum '255' will be white.")
  public Integer getGrey() {
    return grey;
  }
  public void setGrey(Integer grey) {
    this.grey = grey;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    INParam iNParam = (INParam) o;
    return (this.inClass == null ? iNParam.inClass == null : this.inClass.equals(iNParam.inClass)) &&
        (this.min == null ? iNParam.min == null : this.min.equals(iNParam.min)) &&
        (this.max == null ? iNParam.max == null : this.max.equals(iNParam.max)) &&
        (this.drawMode == null ? iNParam.drawMode == null : this.drawMode.equals(iNParam.drawMode)) &&
        (this.grey == null ? iNParam.grey == null : this.grey.equals(iNParam.grey));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.inClass == null ? 0: this.inClass.hashCode());
    result = 31 * result + (this.min == null ? 0: this.min.hashCode());
    result = 31 * result + (this.max == null ? 0: this.max.hashCode());
    result = 31 * result + (this.drawMode == null ? 0: this.drawMode.hashCode());
    result = 31 * result + (this.grey == null ? 0: this.grey.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class INParam {\n");
    
    sb.append("  inClass: ").append(inClass).append("\n");
    sb.append("  min: ").append(min).append("\n");
    sb.append("  max: ").append(max).append("\n");
    sb.append("  drawMode: ").append(drawMode).append("\n");
    sb.append("  grey: ").append(grey).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
