/**
 * Irisnet API
 * Artificial Intelligence (AI) for image- and video-processing in real-time. This is an interactive documentation where you can quickly look up the endpoints and their schemas, while having the opportunity to try things out for yourself.  In the list below, you can see the available endpoints of the API, which can be expanded by clicking on them. Each expanded endpoint lists the request parameters (if available) and the request body (if available). The request body can list some example bodies and the schema, explaining each model in detail.  Additionally you'll find a 'Try it out' button that allows you to enter your custom parameters and custom body and execute that against the API. <b>Be sure to enter your license key to authorize the requests before using this documentation interactively.</b>  The responses section in the expanded endpoint lists the possible responses with their corresponding status codes. If you've executed an API call it will also show you the response from the server.  Underneath the endpoints you'll find the model schemas. These are the models used for the requests and responses. If you click on the right arrow, you can expand the model and get a description of the model and the model parameters. For nested models, you can keep clicking the right arrow for further details.  Clicking the link below the title at the top of this page opens the [OpenAPI specification](https://swagger.io/specification/) (OAS3) in JSON format. The OAS3 Spec allows the generation of clients in many programming languages. There are several free client generators available that can be used to get started easily.
 *
 * The version of the OpenAPI document: v2
 * Contact: info@irisnet.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package de.irisnet.java.client.model;

import java.util.Map;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Describes the current balance of the given license key. A key has a certain amount of credits that can be used for any kind of AI recognition. The license key is invalid, when all of the credits have been used, the license was disabled or expired.
 **/
@ApiModel(description = "Describes the current balance of the given license key. A key has a certain amount of credits that can be used for any kind of AI recognition. The license key is invalid, when all of the credits have been used, the license was disabled or expired.")
public class LicenseInfo {
  
  @SerializedName("creditsUsed")
  private Integer creditsUsed = null;
  @SerializedName("creditsRemaining")
  private Integer creditsRemaining = null;
  @SerializedName("totalCredits")
  private Integer totalCredits = null;
  @SerializedName("licenseKey")
  private String licenseKey = null;
  @SerializedName("privileges")
  private Map<String, String> privileges = null;

  /**
   * Credits used for the license key.
   **/
  @ApiModelProperty(value = "Credits used for the license key.")
  public Integer getCreditsUsed() {
    return creditsUsed;
  }
  public void setCreditsUsed(Integer creditsUsed) {
    this.creditsUsed = creditsUsed;
  }

  /**
   * Credits remaining for the license key.
   **/
  @ApiModelProperty(value = "Credits remaining for the license key.")
  public Integer getCreditsRemaining() {
    return creditsRemaining;
  }
  public void setCreditsRemaining(Integer creditsRemaining) {
    this.creditsRemaining = creditsRemaining;
  }

  /**
   * Total credits contained within the license key.
   **/
  @ApiModelProperty(value = "Total credits contained within the license key.")
  public Integer getTotalCredits() {
    return totalCredits;
  }
  public void setTotalCredits(Integer totalCredits) {
    this.totalCredits = totalCredits;
  }

  /**
   * The license key
   **/
  @ApiModelProperty(value = "The license key")
  public String getLicenseKey() {
    return licenseKey;
  }
  public void setLicenseKey(String licenseKey) {
    this.licenseKey = licenseKey;
  }

  /**
   * A map of privileges
   **/
  @ApiModelProperty(value = "A map of privileges")
  public Map<String, String> getPrivileges() {
    return privileges;
  }
  public void setPrivileges(Map<String, String> privileges) {
    this.privileges = privileges;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LicenseInfo licenseInfo = (LicenseInfo) o;
    return (this.creditsUsed == null ? licenseInfo.creditsUsed == null : this.creditsUsed.equals(licenseInfo.creditsUsed)) &&
        (this.creditsRemaining == null ? licenseInfo.creditsRemaining == null : this.creditsRemaining.equals(licenseInfo.creditsRemaining)) &&
        (this.totalCredits == null ? licenseInfo.totalCredits == null : this.totalCredits.equals(licenseInfo.totalCredits)) &&
        (this.licenseKey == null ? licenseInfo.licenseKey == null : this.licenseKey.equals(licenseInfo.licenseKey)) &&
        (this.privileges == null ? licenseInfo.privileges == null : this.privileges.equals(licenseInfo.privileges));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.creditsUsed == null ? 0: this.creditsUsed.hashCode());
    result = 31 * result + (this.creditsRemaining == null ? 0: this.creditsRemaining.hashCode());
    result = 31 * result + (this.totalCredits == null ? 0: this.totalCredits.hashCode());
    result = 31 * result + (this.licenseKey == null ? 0: this.licenseKey.hashCode());
    result = 31 * result + (this.privileges == null ? 0: this.privileges.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class LicenseInfo {\n");
    
    sb.append("  creditsUsed: ").append(creditsUsed).append("\n");
    sb.append("  creditsRemaining: ").append(creditsRemaining).append("\n");
    sb.append("  totalCredits: ").append(totalCredits).append("\n");
    sb.append("  licenseKey: ").append(licenseKey).append("\n");
    sb.append("  privileges: ").append(privileges).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
