/**
 * Irisnet API
 * Artificial Intelligence (AI) for image- and video-processing in real-time. This is an interactive documentation where you can quickly look up the endpoints and their schemas, while having the opportunity to try things out for yourself.  In the list below, you can see the available endpoints of the API, which can be expanded by clicking on them. Each expanded endpoint lists the request parameters (if available) and the request body (if available). The request body can list some example bodies and the schema, explaining each model in detail.  Additionally you'll find a 'Try it out' button that allows you to enter your custom parameters and custom body and execute that against the API. <b>Be sure to enter your license key to authorize the requests before using this documentation interactively.</b>  The responses section in the expanded endpoint lists the possible responses with their corresponding status codes. If you've executed an API call it will also show you the response from the server.  Underneath the endpoints you'll find the model schemas. These are the models used for the requests and responses. If you click on the right arrow, you can expand the model and get a description of the model and the model parameters. For nested models, you can keep clicking the right arrow for further details.  Clicking the link below the title at the top of this page opens the [OpenAPI specification](https://swagger.io/specification/) (OAS3) in JSON format. The OAS3 Spec allows the generation of clients in many programming languages. There are several free client generators available that can be used to get started easily.
 *
 * The version of the OpenAPI document: v2
 * Contact: info@irisnet.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package de.irisnet.java.client.model;

import java.net.URI;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Response object containing necessary information to start the enduser live document check on the client side.
 **/
@ApiModel(description = "Response object containing necessary information to start the enduser live document check on the client side.")
public class LiveDocumentCheckResponseData {
  
  @SerializedName("eventId")
  private String eventId = null;
  @SerializedName("identToken")
  private String identToken = null;
  @SerializedName("endUserIdentUrl")
  private URI endUserIdentUrl = null;

  /**
   * unique id of this live document check
   **/
  @ApiModelProperty(value = "unique id of this live document check")
  public String getEventId() {
    return eventId;
  }
  public void setEventId(String eventId) {
    this.eventId = eventId;
  }

  /**
   * token to secure the live document check, might be null since already incorporated into endUserIdentUrl
   **/
  @ApiModelProperty(value = "token to secure the live document check, might be null since already incorporated into endUserIdentUrl")
  public String getIdentToken() {
    return identToken;
  }
  public void setIdentToken(String identToken) {
    this.identToken = identToken;
  }

  /**
   * URL to send the enduser to, to start the live document check
   **/
  @ApiModelProperty(value = "URL to send the enduser to, to start the live document check")
  public URI getEndUserIdentUrl() {
    return endUserIdentUrl;
  }
  public void setEndUserIdentUrl(URI endUserIdentUrl) {
    this.endUserIdentUrl = endUserIdentUrl;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LiveDocumentCheckResponseData liveDocumentCheckResponseData = (LiveDocumentCheckResponseData) o;
    return (this.eventId == null ? liveDocumentCheckResponseData.eventId == null : this.eventId.equals(liveDocumentCheckResponseData.eventId)) &&
        (this.identToken == null ? liveDocumentCheckResponseData.identToken == null : this.identToken.equals(liveDocumentCheckResponseData.identToken)) &&
        (this.endUserIdentUrl == null ? liveDocumentCheckResponseData.endUserIdentUrl == null : this.endUserIdentUrl.equals(liveDocumentCheckResponseData.endUserIdentUrl));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.eventId == null ? 0: this.eventId.hashCode());
    result = 31 * result + (this.identToken == null ? 0: this.identToken.hashCode());
    result = 31 * result + (this.endUserIdentUrl == null ? 0: this.endUserIdentUrl.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class LiveDocumentCheckResponseData {\n");
    
    sb.append("  eventId: ").append(eventId).append("\n");
    sb.append("  identToken: ").append(identToken).append("\n");
    sb.append("  endUserIdentUrl: ").append(endUserIdentUrl).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
