/**
 * Irisnet API
 * Artificial Intelligence (AI) for image- and video-processing in real-time. This is an interactive documentation where you can quickly look up the endpoints and their schemas, while having the opportunity to try things out for yourself.  In the list below, you can see the available endpoints of the API, which can be expanded by clicking on them. Each expanded endpoint lists the request parameters (if available) and the request body (if available). The request body can list some example bodies and the schema, explaining each model in detail.  Additionally you'll find a 'Try it out' button that allows you to enter your custom parameters and custom body and execute that against the API. <b>Be sure to enter your license key to authorize the requests before using this documentation interactively.</b>  The responses section in the expanded endpoint lists the possible responses with their corresponding status codes. If you've executed an API call it will also show you the response from the server.  Underneath the endpoints you'll find the model schemas. These are the models used for the requests and responses. If you click on the right arrow, you can expand the model and get a description of the model and the model parameters. For nested models, you can keep clicking the right arrow for further details.  Clicking the link below the title at the top of this page opens the [OpenAPI specification](https://swagger.io/specification/) (OAS3) in JSON format. The OAS3 Spec allows the generation of clients in many programming languages. There are several free client generators available that can be used to get started easily.
 *
 * The version of the OpenAPI document: v2
 * Contact: info@irisnet.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package de.irisnet.java.client.model;

import java.util.Date;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Attributes qualifying the _poaDocument_ classification.
 **/
@ApiModel(description = "Attributes qualifying the _poaDocument_ classification.")
public class PoaDocumentAttribute {
  
  @SerializedName("type")
  private String type = null;
  @SerializedName("name")
  private String name = null;
  public enum DocumentTypeEnum {
     passport,  driving_license,  national_identity_card,  residence_permit,  visa,  bank_statement,  utility_bill,  tax_document,  unidentified,  unknown, 
  };
  @SerializedName("documentType")
  private DocumentTypeEnum documentType = null;
  @SerializedName("issuer")
  private String issuer = null;
  @SerializedName("issuingDate")
  private Date issuingDate = null;
  @SerializedName("address")
  private String address = null;
  @SerializedName("addressCountry")
  private String addressCountry = null;

  /**
   * Used as a type discriminator for json to object conversion.
   **/
  @ApiModelProperty(value = "Used as a type discriminator for json to object conversion.")
  public String getType() {
    return type;
  }
  public void setType(String type) {
    this.type = type;
  }

  /**
   * The document holder's name
   **/
  @ApiModelProperty(value = "The document holder's name")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   * The type of the document
   **/
  @ApiModelProperty(value = "The type of the document")
  public DocumentTypeEnum getDocumentType() {
    return documentType;
  }
  public void setDocumentType(DocumentTypeEnum documentType) {
    this.documentType = documentType;
  }

  /**
   * The issuer of the document
   **/
  @ApiModelProperty(value = "The issuer of the document")
  public String getIssuer() {
    return issuer;
  }
  public void setIssuer(String issuer) {
    this.issuer = issuer;
  }

  /**
   * The issuing date
   **/
  @ApiModelProperty(value = "The issuing date")
  public Date getIssuingDate() {
    return issuingDate;
  }
  public void setIssuingDate(Date issuingDate) {
    this.issuingDate = issuingDate;
  }

  /**
   * The document holder's address
   **/
  @ApiModelProperty(value = "The document holder's address")
  public String getAddress() {
    return address;
  }
  public void setAddress(String address) {
    this.address = address;
  }

  /**
   * The document holders's address country in ISO 3166-1 alpha-2 format
   **/
  @ApiModelProperty(value = "The document holders's address country in ISO 3166-1 alpha-2 format")
  public String getAddressCountry() {
    return addressCountry;
  }
  public void setAddressCountry(String addressCountry) {
    this.addressCountry = addressCountry;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PoaDocumentAttribute poaDocumentAttribute = (PoaDocumentAttribute) o;
    return (this.type == null ? poaDocumentAttribute.type == null : this.type.equals(poaDocumentAttribute.type)) &&
        (this.name == null ? poaDocumentAttribute.name == null : this.name.equals(poaDocumentAttribute.name)) &&
        (this.documentType == null ? poaDocumentAttribute.documentType == null : this.documentType.equals(poaDocumentAttribute.documentType)) &&
        (this.issuer == null ? poaDocumentAttribute.issuer == null : this.issuer.equals(poaDocumentAttribute.issuer)) &&
        (this.issuingDate == null ? poaDocumentAttribute.issuingDate == null : this.issuingDate.equals(poaDocumentAttribute.issuingDate)) &&
        (this.address == null ? poaDocumentAttribute.address == null : this.address.equals(poaDocumentAttribute.address)) &&
        (this.addressCountry == null ? poaDocumentAttribute.addressCountry == null : this.addressCountry.equals(poaDocumentAttribute.addressCountry));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.type == null ? 0: this.type.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.documentType == null ? 0: this.documentType.hashCode());
    result = 31 * result + (this.issuer == null ? 0: this.issuer.hashCode());
    result = 31 * result + (this.issuingDate == null ? 0: this.issuingDate.hashCode());
    result = 31 * result + (this.address == null ? 0: this.address.hashCode());
    result = 31 * result + (this.addressCountry == null ? 0: this.addressCountry.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class PoaDocumentAttribute {\n");
    
    sb.append("  type: ").append(type).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  documentType: ").append(documentType).append("\n");
    sb.append("  issuer: ").append(issuer).append("\n");
    sb.append("  issuingDate: ").append(issuingDate).append("\n");
    sb.append("  address: ").append(address).append("\n");
    sb.append("  addressCountry: ").append(addressCountry).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
