/**
 * Irisnet API
 * Artificial Intelligence (AI) for image- and video-processing in real-time. This is an interactive documentation where you can quickly look up the endpoints and their schemas, while having the opportunity to try things out for yourself.  In the list below, you can see the available endpoints of the API, which can be expanded by clicking on them. Each expanded endpoint lists the request parameters (if available) and the request body (if available). The request body can list some example bodies and the schema, explaining each model in detail.  Additionally you'll find a 'Try it out' button that allows you to enter your custom parameters and custom body and execute that against the API. <b>Be sure to enter your license key to authorize the requests before using this documentation interactively.</b>  The responses section in the expanded endpoint lists the possible responses with their corresponding status codes. If you've executed an API call it will also show you the response from the server.  Underneath the endpoints you'll find the model schemas. These are the models used for the requests and responses. If you click on the right arrow, you can expand the model and get a description of the model and the model parameters. For nested models, you can keep clicking the right arrow for further details.  Clicking the link below the title at the top of this page opens the [OpenAPI specification](https://swagger.io/specification/) (OAS3) in JSON format. The OAS3 Spec allows the generation of clients in many programming languages. There are several free client generators available that can be used to get started easily.
 *
 * The version of the OpenAPI document: v2
 * Contact: info@irisnet.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package de.irisnet.java.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Contains information on poaDocument sub-checks
 **/
@ApiModel(description = "Contains information on poaDocument sub-checks")
public class PoaDocumentSubChecks {
  
  public enum FirstNameEnum {
     passed,  failed,  not_processed, 
  };
  @SerializedName("firstName")
  private FirstNameEnum firstName = null;
  public enum LastNameEnum {
     passed,  failed,  not_processed, 
  };
  @SerializedName("lastName")
  private LastNameEnum lastName = null;
  public enum DocumentAgeEnum {
     passed,  failed,  not_processed, 
  };
  @SerializedName("documentAge")
  private DocumentAgeEnum documentAge = null;
  public enum IpOriginatesInAddressCountryEnum {
     passed,  failed,  not_processed, 
  };
  @SerializedName("ipOriginatesInAddressCountry")
  private IpOriginatesInAddressCountryEnum ipOriginatesInAddressCountry = null;
  public enum IpNearbyAddressEnum {
     passed,  failed,  not_processed, 
  };
  @SerializedName("ipNearbyAddress")
  private IpNearbyAddressEnum ipNearbyAddress = null;

  /**
   * Indicates whether the first name is valid
   **/
  @ApiModelProperty(value = "Indicates whether the first name is valid")
  public FirstNameEnum getFirstName() {
    return firstName;
  }
  public void setFirstName(FirstNameEnum firstName) {
    this.firstName = firstName;
  }

  /**
   * Indicates whether the last name is valid
   **/
  @ApiModelProperty(value = "Indicates whether the last name is valid")
  public LastNameEnum getLastName() {
    return lastName;
  }
  public void setLastName(LastNameEnum lastName) {
    this.lastName = lastName;
  }

  /**
   * Indicates whether the age of the document is valid (not older than 3 months)
   **/
  @ApiModelProperty(value = "Indicates whether the age of the document is valid (not older than 3 months)")
  public DocumentAgeEnum getDocumentAge() {
    return documentAge;
  }
  public void setDocumentAge(DocumentAgeEnum documentAge) {
    this.documentAge = documentAge;
  }

  /**
   * Indicates whether the client IP originates in the country of the address
   **/
  @ApiModelProperty(value = "Indicates whether the client IP originates in the country of the address")
  public IpOriginatesInAddressCountryEnum getIpOriginatesInAddressCountry() {
    return ipOriginatesInAddressCountry;
  }
  public void setIpOriginatesInAddressCountry(IpOriginatesInAddressCountryEnum ipOriginatesInAddressCountry) {
    this.ipOriginatesInAddressCountry = ipOriginatesInAddressCountry;
  }

  /**
   * Indicates whether the client IP is in reasonable distance from the address
   **/
  @ApiModelProperty(value = "Indicates whether the client IP is in reasonable distance from the address")
  public IpNearbyAddressEnum getIpNearbyAddress() {
    return ipNearbyAddress;
  }
  public void setIpNearbyAddress(IpNearbyAddressEnum ipNearbyAddress) {
    this.ipNearbyAddress = ipNearbyAddress;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PoaDocumentSubChecks poaDocumentSubChecks = (PoaDocumentSubChecks) o;
    return (this.firstName == null ? poaDocumentSubChecks.firstName == null : this.firstName.equals(poaDocumentSubChecks.firstName)) &&
        (this.lastName == null ? poaDocumentSubChecks.lastName == null : this.lastName.equals(poaDocumentSubChecks.lastName)) &&
        (this.documentAge == null ? poaDocumentSubChecks.documentAge == null : this.documentAge.equals(poaDocumentSubChecks.documentAge)) &&
        (this.ipOriginatesInAddressCountry == null ? poaDocumentSubChecks.ipOriginatesInAddressCountry == null : this.ipOriginatesInAddressCountry.equals(poaDocumentSubChecks.ipOriginatesInAddressCountry)) &&
        (this.ipNearbyAddress == null ? poaDocumentSubChecks.ipNearbyAddress == null : this.ipNearbyAddress.equals(poaDocumentSubChecks.ipNearbyAddress));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.firstName == null ? 0: this.firstName.hashCode());
    result = 31 * result + (this.lastName == null ? 0: this.lastName.hashCode());
    result = 31 * result + (this.documentAge == null ? 0: this.documentAge.hashCode());
    result = 31 * result + (this.ipOriginatesInAddressCountry == null ? 0: this.ipOriginatesInAddressCountry.hashCode());
    result = 31 * result + (this.ipNearbyAddress == null ? 0: this.ipNearbyAddress.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class PoaDocumentSubChecks {\n");
    
    sb.append("  firstName: ").append(firstName).append("\n");
    sb.append("  lastName: ").append(lastName).append("\n");
    sb.append("  documentAge: ").append(documentAge).append("\n");
    sb.append("  ipOriginatesInAddressCountry: ").append(ipOriginatesInAddressCountry).append("\n");
    sb.append("  ipNearbyAddress: ").append(ipNearbyAddress).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
