/**
 * Irisnet API
 * Artificial Intelligence (AI) for image- and video-processing in real-time. This is an interactive documentation where you can quickly look up the endpoints and their schemas, while having the opportunity to try things out for yourself.  In the list below, you can see the available endpoints of the API, which can be expanded by clicking on them. Each expanded endpoint lists the request parameters (if available) and the request body (if available). The request body can list some example bodies and the schema, explaining each model in detail.  Additionally you'll find a 'Try it out' button that allows you to enter your custom parameters and custom body and execute that against the API. <b>Be sure to enter your license key to authorize the requests before using this documentation interactively.</b>  The responses section in the expanded endpoint lists the possible responses with their corresponding status codes. If you've executed an API call it will also show you the response from the server.  Underneath the endpoints you'll find the model schemas. These are the models used for the requests and responses. If you click on the right arrow, you can expand the model and get a description of the model and the model parameters. For nested models, you can keep clicking the right arrow for further details.  Clicking the link below the title at the top of this page opens the [OpenAPI specification](https://swagger.io/specification/) (OAS3) in JSON format. The OAS3 Spec allows the generation of clients in many programming languages. There are several free client generators available that can be used to get started easily.
 *
 * The version of the OpenAPI document: v2
 * Contact: info@irisnet.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package de.irisnet.java.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Describes the bounds of a rectangle starting from the center.
 **/
@ApiModel(description = "Describes the bounds of a rectangle starting from the center.")
public class Rectangle {
  
  @SerializedName("x0")
  private Float x0 = null;
  @SerializedName("y0")
  private Float y0 = null;
  @SerializedName("width")
  private Float width = null;
  @SerializedName("height")
  private Float height = null;

  /**
   * The center of the rectangle in the horizontal (x) direction.
   **/
  @ApiModelProperty(value = "The center of the rectangle in the horizontal (x) direction.")
  public Float getX0() {
    return x0;
  }
  public void setX0(Float x0) {
    this.x0 = x0;
  }

  /**
   * The center of the rectangle in the vertical (y) direction.
   **/
  @ApiModelProperty(value = "The center of the rectangle in the vertical (y) direction.")
  public Float getY0() {
    return y0;
  }
  public void setY0(Float y0) {
    this.y0 = y0;
  }

  /**
   * The total width of the rectangle in the horizontal (x) direction. Use _x0 - width / 2_ and _x0 + width / 2_ to get the left and right edges of the rectangle.
   **/
  @ApiModelProperty(value = "The total width of the rectangle in the horizontal (x) direction. Use _x0 - width / 2_ and _x0 + width / 2_ to get the left and right edges of the rectangle.")
  public Float getWidth() {
    return width;
  }
  public void setWidth(Float width) {
    this.width = width;
  }

  /**
   * The total height of the rectangle in the vertical (y) direction. Use _y0 - height / 2_ and _y0 + height / 2_ to get the top and bottom edges of the rectangle.
   **/
  @ApiModelProperty(value = "The total height of the rectangle in the vertical (y) direction. Use _y0 - height / 2_ and _y0 + height / 2_ to get the top and bottom edges of the rectangle.")
  public Float getHeight() {
    return height;
  }
  public void setHeight(Float height) {
    this.height = height;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Rectangle rectangle = (Rectangle) o;
    return (this.x0 == null ? rectangle.x0 == null : this.x0.equals(rectangle.x0)) &&
        (this.y0 == null ? rectangle.y0 == null : this.y0.equals(rectangle.y0)) &&
        (this.width == null ? rectangle.width == null : this.width.equals(rectangle.width)) &&
        (this.height == null ? rectangle.height == null : this.height.equals(rectangle.height));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.x0 == null ? 0: this.x0.hashCode());
    result = 31 * result + (this.y0 == null ? 0: this.y0.hashCode());
    result = 31 * result + (this.width == null ? 0: this.width.hashCode());
    result = 31 * result + (this.height == null ? 0: this.height.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Rectangle {\n");
    
    sb.append("  x0: ").append(x0).append("\n");
    sb.append("  y0: ").append(y0).append("\n");
    sb.append("  width: ").append(width).append("\n");
    sb.append("  height: ").append(height).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
